url: "https://casadealabanza.church" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Casa De Alabanza" # the name of your site, e.g. ACME Corp.
site: "Casa De Alabanza"
